import React, {useState} from 'react';
import './App.css';
import {Button} from "@material-ui/core";

const App: React.FC = () => {

    let [index, setIndex] = useState(0);

    function getRandomIndex(): void {
        setIndex(Math.floor(Math.random() * wimlts.length))
    }

    const wimlts: string[] = [
      'Who is most likely to listen classical music?',
      'Who is most likely to go the museum very often?',
      'Who is most likely to be rich?',
      'Who is most likely to be poor?',
      'Who is most likely to be in a choir?',
      'Who is most likely to go Justin Biebers concert?',
      'Who is most likely to give all their money  charity?',
      'Who is most likely to always be happy?',
      'Who is most likely to watch porn as soon as they wake up?',
      'Who is most likely to get married first?',
      'Who is most likely to win a Nobel prize?',
      'Who is most likely to kill someone accidentally?',
      'Who is most likely to kill someone on purpose?',
      'Who is most likely to die of something stupid?',
      'Who is most likely to get in a fight?',
      'Who is most likely to fail a simple test?',
      'Who is most likely to become a multi-millionaire?',
      'Who is most likely to get arrested for walking around naked?',
      'Who is most likely to have two girlfriends or boyfriends at one time?',
      'Who is most likely to be the first one die in a zombie apocalypse?',
      'Who is most likely to win a lottery?',
      'Who is most likely to take their clothes off in a public setting?',
      'Who is most likely to sleep somewhere else because they have seen a spider on their bed?',
      'Who is most likely to dye their hair blonde?',
      'Who is most likely to end up homeless?',
      'Who is most likely to accidentally get killed?',
      'Who is most likely to change their gender?',
      'Who is most likely to experience a heart attack?',
      'Who is most likely to become famous?',
      'Who is most likely to cheat on their girlfriend/boyfriend?',
      'Who is most likely to date a celebrity?',
      'Who is most likely to read a hundred books in a year?',
      'Who is most likely to start a family?',
      'Who is most likely to spend all their money in a casino?',
      'Who is most likely to write a best-selling book?',
      'Who is most likely to accomplish their goals?',
      'Who is most likely to get a girl by writing her a poem?',
      'Who is most likely to study at Harvard University?',
      'Who is most likely to meet President Trump?',
      'Who is most likely to abuse someone?',
      'Who is most likely to move to another continent?',
      'Who is most likely to visit Australia?',
      'Who is most likely to be a single parent?',
      'Who is most likely to visit the Taj Mahal?',
      'Who is most likely to visit the pyramids in Egypt?',
      'Who is most likely to take drugs?',
      'Who is most likely to have plastic surgery?',
      'Who is most likely to become a porn star?',
      'Who is most likely to have sex for money?',
      'Who is most likely to become an astronaut?',
      'Who is most likely to kill their pet?',
      'Who is most likely to have a foot fetish?',
      'Who is most likely to have sex on a daily basis?',
      'Who is most likely to become gay?',
      'Who is most likely to always be loyal?',
      'Who is most likely to dedicate their life to help others?',
      'Who is most likely to travel the world?',
      'Who is most likely to have a long-lasting, serious relationship?',
      'Who is most likely to make a long-distance relationship work?',
      'Who is most likely to become poor?',
      'Who is most likely to become a vampire?',
      'Who is most likely to become a CEO of a company?',
      'Who is most likely to be a robot?',
      'Who is most likely to fail all of their exams?',
      'Who is most likely to learn Japanese?',
      'Who is most likely to go skydiving?',
      'Who is most likely to fall for Hugh Laurie?',
      'Who is most likely to learn how to play the harp?',
      'Who is most likely to quit their present job?',
      'Who is most likely to play Fortnite for days?',
      'Who is most likely to adopt a child?',
      'Who is most likely to win a Nobel Peace Prize?',
      'Who is most likely to obey their parents?',
      'Who is most likely to touch a random woman’s butt?',
      'Who is most likely to be racist?',
      'Who is most likely to be sexist?',
      'Who is most likely to smoke weed with their kids?',
      'Who is most likely to get drunk tonight?',
      'Who is most likely to dance in the rain?',
      'Who is most likely to exercise daily?',
      'Who is most likely to become a philosopher?',
      'Who is most likely to become a psychologist?',
      'Who is most likely to win a Guinness World Record for something very stupid?',
      'Who is most likely to become the kindest person in the world?',
      'Who is most likely to climb Mount Everest?',
      'Who is most likely to fart loudly in a crowded room?',
      'Who is most likely to dress like Sailor Moon?',
      'Who is most likely to forget the birthday of their partner?',
      'Who is most likely to cry in public?',
      'Who is most likely to live with their parents after they’ve turned 30?',
      'Who is most likely to star in a movie as the villain?',
      'Who is most likely to be like their parents?',
      'Who is most likely to become the prettiest girl in the world?',
      'Who is most likely to stay close friends?',
      'Who is most likely to catch their parents having sex?',
      'Who is most likely to find a million dollars on the road?',
      'Who is most likely to become a cat lady?',
      'Who is most likely to stay forever single?',
      'Who is most likely to leave Earth and live on Mars?',
      'Who is most likely to be the last person on earth?',
      'Who is most likely to kill an animal?',
      'Who is most likely to kill a person for money?',
      'Who is most likely to collect snakes?',
      'Who is most likely to have more than one girlfriend at a time?',
      'Who is most likely to change their religion?',
      'Who is most likely to finish their work on time?',
      'Who is most likely to fall asleep during class?',
      'Who is most likely to help the poor?',
      'Who is most likely to get sick?',
      'Who is most likely to wear black for the rest of their life?',
      'Who is most likely to find the love of their life at a party?',
      'Who is most likely to eat spicy food every day?',
      'Who is most likely to become a vegan?',
      'Who is most likely to move to Hawaii?',
      'Who is most likely to have more than 5 children?',
      'Who is most likely to worship the Norse Gods?',
      'Who is most likely to become a successful businessman?',
      'Who is most likely to find a job they love?',
      'Who is most likely to open up a bar?',
      'Who is most likely to drink beer for the rest of their life?',
      'Who is most likely to get married before anyone else?',
      'Who is most likely to become an actor?',
      'Who is most likely to watch porn when they wake up in the morning?',
      'Who is most likely to laugh at lame jokes?',
      'Who is most likely to buy healing crystals?',
      'Who is most likely to study naturopathy?',
      'Who is most likely to color their hair in a weird color?',
      'Who is most likely to go to a thrash metal concert?',
      'Who is most likely to become a great leader?',
      'Who is most likely to collect butterflies?',
      'Who is most likely to hug everyone in the room?',
      'Who is most likely to eat snow?',
      'Who is most likely to have the highest grades?',
      'Who is most likely to date Justin Bieber?',
      'Who is most likely to be on a reality show?',
      'Who is most likely to marry a celebrity?',
      'Who is most likely to do weird things in public?',
      'Who is most likely to be so bored that they yawn all the time?',
      'Who is most likely to become a doctor?',
      'Who is most likely to watch chick flicks with their girlfriend/boyfriend?',
      'Who is most likely to eat raw eggs?',
      'Who is most likely to suffer over a break-up?',
      'Who is most likely to meet a genie?',
      'Who is most likely to catch a golden fish?',
      'Who is most likely to catch an STD?',
      'Who is most likely to owe you money?',
      'Who is most likely to become the eighth wonder of the world?',
      'Who is most likely to fight with their partner all the time?',
      'Who is most likely to get married for the money?',
      'Who is most likely to start a relationship with someone just because they have a great car?',
      'Who is most likely to date a real witch?',
      'Who is most likely to have a cute daughter?',
      'Who is most likely to work at NASA?',
      'Who is most likely to work at Microsoft?',
      'Who is most likely to get kicked out of class?',
      'Who is most likely to donate money to the poor?',
      'Who is most likely to become a minimalist?',
      'Who is most likely to start living in a van?',
      'Who is most likely to eat their birthday cake alone?',
      'Who is most likely to get a tattoo?',
      'Who is most likely to have a mental disorder?',
      'Who is most likely to own a creepy doll?',
      'Who is most likely to live in a haunted house?',
      'Who is most likely to get bullied in school?',
      'Who is most likely to have a wet dream tonight?',
      'Who is most likely to draw a picture of their penis on a wall?',
      'Who is most likely to send a dick pic?',
      'Who is most likely to own thousands of dresses?',
      'Who is most likely to become a pilot?',
      'Who is most likely to treat their wife well?',
      'Who is most likely to take the stars off the sky for their loved one?',
      'Who is most likely to eat raw meat for money?',
      'Who is most likely to cry because of a movie scene?',
      'Who is most likely to become a psychopath?',
      'Who is most likely to be horny a lot?',
      'Who is most likely to have a crush on their boss?',
      'Who is most likely to become addicted to sex?',
      'Who is most likely to have never been in love?',
      'Who is most likely to spend most of their time being productive?',
      'Who is most likely to be heartbroken?',
      'Who is most likely to do something big in their life?',
      'Who is most likely to be interested in the same sex?',
      'Who is most likely to eat the most?',
      'Who is most likely to be a perfect kisser?',
      'Who is most likely to backstab their friends?',
      'Who is most likely to get a piercing?',
      'Who is most likely to become an artist?',
      'Who is most likely to fall in love in a foreign country?',
      'Who is most likely to admit when they’re wrong?',
      'Who is most likely to have a failed marriage?',
      'Who is most likely to outlive a zombie apocalypse?',
      'Who is most likely to burp in a crowded room?',
      'Who is most likely to get pregnant?',
      'Who is most likely to have a secret crush on a celebrity?',
      'Who is most likely to be filthy rich?',
      'Who is most likely to go bankrupt?',
      'Who is most likely to outlive us all?',
      'Who is most likely to become the next senator of our state?',
      'Who is most likely to have legal problems?',
      'Who is most likely to have a bunch of children?',
      'Who is most likely to end up on a deserted island (and who will they be accompanied by)?',
      'Who is most likely to become an actual singer?',
      'Who is most likely to win a burger-eating contest?',
      'Who is most likely to set a world record at beer pong?',
      'Who is most likely to break the world record in sleeping?',
      'Who is most likely to become an Instagram star?',
      'Who is most likely to move abroad?',
      'Who is most likely to buy a house or an apartment someday?',
      'Who is most likely to raise sheep and live in the countryside?',
      'Who is most likely to star in a romantic movie?',
      'Who is most likely to secretly watch porn?',
      'Who is most likely to know the names of all the famous pornstars?',
      'Who is most likely to send nudes to their crush?',
      'Who is most likely to have some hidden, kinky sexual desires?',
      'Who is most likely to move to the North Pole?',
      'Who is most likely to be the dancing queen/king of the nursing home?',
      'Who is most likely to have a friend with benefits?',
      'Who is most likely to have a cuddle buddy?',
      'Who is most likely to have an affair once they get married?',
      'Who is most likely to stay faithful and loyal to their partner?',
      'Who is most likely to change their name?',
      'Who is most likely to join the military?',
      'Who is most likely to become a military wife/husband?',
      'Who is most likely to be late to their own wedding?',
      'Who is most likely to find a part-time job as a waiter/waitress?',
      'Who is most likely to quit their day job and work at McDonald’s?',
      'Who is most likely to walk along the Great Wall of China?',
      'Who is most likely to learn a martial art?',
      'Who is most likely to be a cocktail master?',
      'Who is most likely to be an expert at all sorts of alcoholic drinks?',
      'Who is most likely to fall in love on their trip to Cuba?',
      'Who is most likely to text their ex when they are drunk?',
      'Who is most likely to have drunk sex?',
      'Who is most likely to have a one-night-stand?',
      'Who is most likely to listen to same lame pop song and hide it from their friends?',
      'Who is most likely to become a priest/nun?',
      'Who is most likely to get divorced because of their gaming addiction?',
      'Who is most likely to earn some serious money due to their groundbreaking idea?',
      'Who is most likely to already have a tattoo that is very well hidden?',
      'Who is most likely to fall asleep on public transportation?',
      'Who is most likely to become a stripper?',
      'Who is most likely to go crazy and even spend some time in a looney bin, a few years from now?',
      'Who is most likely to have something embarrassing about them go viral'
    ];

    return (
        <header className="App-header">
            <div className="App">
                <p>{wimlts[index]}</p>
            </div>
            <div>
                <Button variant="contained" onClick={() => getRandomIndex()} color="primary" size="large">
                    Next
                </Button>
            </div>
        </header>

    );
}

export default App;
